fix: send `Teams` error message on system failure
nlnwa/hermetic pull request #23
Opened 2023-11-08 06:47 UTC by trym-b

# Motivation

If something unexpected happens, like an unhandled error, a message will be sent to `Teams` notifying the users that something is wrong. This will reduce the cognitive load of the users since they don't have to check the logs to see if something is wrong.

# Future work

The errors could be unwrapped for a nicer user experience, but at this point, it seems like premature optimization.

2023-11-08 12:51 UTC, maeb requested changes

2023-11-08 12:51 UTC, maeb commented on cmd/send/send.go
> +	return nil
I argue that the program should return the original error as well as send a message to teams. This is important because when run in kubernetes as a pod in a deployment, kubernetes will crashloopbackoff the container if an error occured but will restart the container indefinitely without a delay if the program exited with error code 0.


```suggestion
	return err
```

2023-11-08 12:51 UTC, maeb commented on cmd/verify/verify.go
> +	return nil
See explanation above (transfer).

```suggestion
	return err
```

2023-11-08 12:53 UTC, maeb commented on cmd/send/send.go
> +		return err
This error message should just be logged and not returned, because we would like to return the original error message and not the error that the teams message failed to be sent.

2023-11-09 06:06 UTC, trym-b commented on cmd/send/send.go
> +	return nil
My bad, my intent was to return the error message, but for some reason I did not. Fixed in https://github.com/nlnwa/hermetic/pull/23/commits/c02afc6baaf37d389b563024aa4370b5ee5565cb

2023-11-09 06:06 UTC, trym-b commented on cmd/verify/verify.go
> +	return nil
My bad, my intent was to return the error message, but for some reason I did not. Fixed in https://github.com/nlnwa/hermetic/pull/23/commits/c02afc6baaf37d389b563024aa4370b5ee5565cb

2023-11-09 06:15 UTC, trym-b commented on cmd/send/send.go
> +		return err
If we are failing to send a message to teams, we would also know that it failed, otherwise how would we know that it failed? IMO we are simply wrapping the original error with the teams error, so we will get a nested error message that contains all of the information.

Say you have the scenario where an original error moves through a system and triggers other errors along the way:

```go
func someFunc01() error {
    print("someFunc01")
    return fmt.Errorf("someFunc01 error")
}

func someFunc02() error {
    err := someFunc01()
    if err != nil {
        return fmt.Errorf("someFunc02 error: %w", err) // not appending the error here would be a mistake IMO
    }
    return nil
}

func main() {
    err := someFunc02()
    if err != nil {
        fmt.Println(err)
    }
}
```

It is crucial for a developer to know what went wrong, and silently dropping an error message can lead to confusion. 

Or am I misunderstanding something

2023-11-09 14:05 UTC, maeb commented on cmd/send/send.go
> +		return err
I misread the code which is actually doing what I proposed.

2023-11-09 14:05 UTC, maeb commented on cmd/verify/verify.go
> +		return err
The code is doing what I am proposing. My bad.

2023-11-09 14:06 UTC, maeb approved these changes
LGTM

2023-11-09 15:28 UTC, trym-b commented
Thanks for the review

2023-11-09 15:34 UTC, merged