feat: Add optional flag for sending confirm message to API
nlnwa/hermetic pull request #52
Opened 2024-08-30 10:25 UTC by andrbo

When hermetic recevies a confirm message, we want to relay the response from DPS to update a database with the files location in DPS.

2024-08-30 11:22 UTC, maeb requested changes

2024-08-30 11:22 UTC, maeb commented on internal/verify/confirm/confirm.go
> +	url := fmt.Sprintf("%s%s", baseUrl, response.Identifier)
Use `url.JoinPath`

2024-08-30 11:41 UTC, andrbo commented on internal/verify/confirm/confirm.go
> +	url := fmt.Sprintf("%s%s", baseUrl, response.Identifier)
Done

2024-09-24 06:41 UTC, frodstee commented on cmd/verify/confirm/confirm.go
> +	if confirmMessageReceiverUrl != "" {
Er denne if else nødvendig. Kontroll om "confirmMessageReceiverUrl" er utfylt eller ikke gjøres i metoden.

2024-09-27 07:10 UTC, andrbo commented on cmd/verify/confirm/confirm.go
> +	if confirmMessageReceiverUrl != "" {
Removed

2024-09-27 07:52 UTC, frodstee approved these changes

2024-09-27 07:57 UTC, merged