feat: add common arguments
nlnwa/hermetic pull request #6
Opened 2023-08-04 09:03 UTC by trym-b

This commit adds `--teams-webhook-notification-url` as a top-level argument and also adds parsing of this flag and the existing `--kafka-endpoints` argument.

The argument names have also been de-duplicated.

Both will be used by the `verification` and `transfer` implementations in later commits.

2023-08-11 08:46 UTC, trym-b commented on internal/common/common.go
> +	kafkaEndpoints, kafkaEndpointsError := cmd.Flags().GetStringSlice(KafkaEndpointsFlagName)
After an IRL meeting with @johnerikhalse I will take a look at `StringSliceVar` and similar functions to reduce the amount of code. I will also take a look around to see what the most idiomatic way of working with `cobra` is.

2023-08-11 11:38 UTC, trym-b commented on internal/common/common.go
> +	kafkaEndpoints, kafkaEndpointsError := cmd.Flags().GetStringSlice(KafkaEndpointsFlagName)
I discovered that using `cobra` was probably not the best choice for argument parsing in this case, but I do not want to rewrite the code at this point.

I did rename the package as we discussed, but at this point I am tempted at leaving the argument handling as is and next time look into alternatives to `cobra`

2023-09-05 11:21 UTC, johnerikhalse commented on cmd/root.go
> +	rootCommand.PersistentFlags().String(common_flags.TeamsWebhookNotificationUrlFlagName, "", "url to teams webhook for notifications")
Utilize Corba for error handling. See also suggested change for `common_flags.go`

```suggestion
	rootCommand.PersistentFlags().StringSliceVar(&common_flags.KafkaEndpoints, "kafka-endpoints", []string{}, "list of kafka endpoints")
	rootCommand.PersistentFlags().StringVar(&common_flags.TeamsWebhookNotificationUrl, "teams-webhook-notification-url", "", "url to teams webhook for notifications")
```

2023-09-05 11:21 UTC, johnerikhalse commented on internal/common_flags/common_flags.go
> +}
```suggestion
var (
	KafkaEndpoints              []string
	TeamsWebhookNotificationUrl string
)
```

Together with the suggested change to `root.go` this will simplify code.
When you want to use the flag value, it is as simple as
```golang
fmt.Println(common_flags.KafkaEndpoints, common_flags.TeamsWebhookNotificationUrl)
```

2023-09-06 05:38 UTC, trym-b commented
Thanks for the comments @johnerikhalse, unfortunately, I am unable to make any progress on this PR until at least the middle of next week, so I will move this one to draft until then.

2023-09-28 10:36 UTC, trym-b commented on internal/common_flags/common_flags.go
> +}
Thanks for the suggestions, since last time I looked at the code I think I changed my mind and agree with that this is much shorter and less error prone.

2023-09-28 11:26 UTC, trym-b commented
Ready for next round @johnerikhalse

2023-09-28 11:44 UTC, trym-b commented
> It can be argued that all flags are available through the `cmd *cobra.Command` argument in the `Run/RunE` function of every cobra command and subcommand and as such don't need to be put in it's own package as global mutable variables.

Sure, the less global the better. How would you have done it if I might ask?

2023-09-28 11:45 UTC, maeb commented on cmd/root.go
> +	rootCommand.PersistentFlags().StringSliceVar(&common_flags.KafkaEndpoints, "kafka-endpoints", []string{}, "list of kafka endpoints")
```shell
// package level scope constant (maybe in another package)
const PersistentFlagKafkaEndpoints = "kafka-endpoints"

	_ = rootCommand.PersistentFlags().StringSlice(PersistentFlagKafkaEndpoints, []string{}, "list of kafka endpoints")
```

If we follow this pattern the subcommand needing this flag would access it as:
```shell
     runE: func(cmd *cobra.Command, args []string) {
           kafkaEndpoint := cmd.PersistentFlags().GetString(packagewithflagconstant.PersistentFlagKafkaEndpoint)
     }
```

2023-09-28 11:57 UTC, trym-b commented on cmd/root.go
> +	rootCommand.PersistentFlags().StringSliceVar(&common_flags.KafkaEndpoints, "kafka-endpoints", []string{}, "list of kafka endpoints")
Do you know a repo or two that uses `cobra` the way we do that we can use for reference?

2023-09-29 06:24 UTC, trym-b commented on cmd/root.go
> +	rootCommand.PersistentFlags().StringSliceVar(&common_flags.KafkaEndpoints, "kafka-endpoints", []string{}, "list of kafka endpoints")
After a round of live code review with @maeb , we decided to rewrite the argument handling slightly.

2023-09-29 06:24 UTC, trym-b commented
Ready for next round

2023-09-29 08:57 UTC, johnerikhalse requested changes

2023-09-29 08:57 UTC, johnerikhalse commented on cmd/root.go
> +	if kafkaFlagError := rootCommand.MarkPersistentFlagRequired(common_flags.KafkaEndpoints); kafkaFlagError != nil {
Use go style naming
```suggestion
	if err := rootCommand.MarkPersistentFlagRequired(common_flags.KafkaEndpoints); err != nil {
```

2023-09-29 08:57 UTC, johnerikhalse commented on cmd/root.go
> +	if teamsFlagError := rootCommand.MarkPersistentFlagRequired(common_flags.TeamsWebhookNotificationUrl); teamsFlagError != nil {
```suggestion
	if err := rootCommand.MarkPersistentFlagRequired(common_flags.TeamsWebhookNotificationUrl); err != nil {
```

2023-09-29 09:06 UTC, johnerikhalse commented
> It can be argued that all flags are available through the `cmd *cobra.Command` argument in the `Run/RunE` function of every cobra command and subcommand and as such don't need to be put in it's own package as global mutable variables.

It can also be argued that every command can set the value of a flag and as such is almost global mutable. With my solution you get guaranteed error handling which I think is more important and it's easier to read.

2023-09-29 09:31 UTC, trym-b commented
Ready for next round

2023-10-02 08:30 UTC, trym-b commented
Ready for next round

2023-10-02 09:32 UTC, johnerikhalse approved these changes

2023-10-02 09:38 UTC, merged